version: "3.7"

services:
  spotify-ripper-web:
    build: ./

    restart: unless-stopped

    ports:
      - "80:3000"
      - "81:3300"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${EXPORT_PATH}:/ripped_music

    environment:
      EXPORT_PATH: ${EXPORT_PATH}
